config/routes.rb
Rails.application.routes.draw do

# デバイス関係
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers:{
  sessions: "admin/sessions"
  }
  

# ユーザー側
  root to: 'homes#index'
  resources :homes,only: [:index]
  resources :items

  resources :items do
    resources :comments, only: [:create,:destroy],module: 'items'
    resource :likes, only: [:create,:destroy],module: 'items'
    collection do
    resources :searches, only: [:index],module: 'items'
    end
  end

  resources :users do
    # get 'users/my_page' => 'users#show'
    get 'confirm' => "users#confirm"
    patch 'withdraw' => 'users#withdraw'
  end
    
  # resources :users, only: [:edit, :update]
  
  # resources :users do
  #   resources :comments, only: [:create,:destroy],module: 'users'
  # end

  resources :users do
    resources :relationships, only: [:create,:destroy],module: 'users'
  end


# 管理者ルーティング
  namespace :admin do
    resources :comments, only: [:index, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:show, :destroy]
    root to: 'comments#index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :item
  
  validates :comment, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  
  def index
    @comments = Comment.all
    @users = User.all
  end
  
  def destroy
    @comments = Comment.find(params[:id])
    @comments.destroy
    redirect_to request.referer
  end
end

app/controllers/items/comments_controller.rb
class Items::CommentsController < ApplicationController
  def create
    item = Item.find(params[:item_id])
    comment = current_user.comments.new(comment_params)
    comment.item_id = item.id
    if comment.save
      redirect_to item_path(item)
    else
      @item = item
      @comment = comment
      render 'items/show'
    end
  end

  def destroy
    item = Item.find(params[:item_id])
    comment = Comment.find(params[:id])
    
    if comment.user_id == current_user.id
      Comment.find(params[:id]).destroy
      redirect_to item_path(item)
    else
      redirect_to item_path(item)
      flash[:alert] = "他人の投稿は削除できません"
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/helpers/users/comments_helper.rb
module Users::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container mt-5">
<h3>コメント一覧</h3>
<table class="table mt-3">
  <tr>
    <th class="col-2">名前</th>
    <th class="col-8">コメント</th>
    <th class="col-1"></th>
    <th class="col-1"></th>
  </tr>
<% @comments.each do |comment| %>
  <tr>
    <td class="col-2"><%=link_to @users.find(comment.user_id).name, admin_user_path(comment.user_id) %></td>
    <td class="col-8"><%= comment.comment %></td>
    <td class="col-1"><%= comment.created_at.strftime('%Y/%m/%d') %></td>
    <td class="col-1">
    <%= link_to '削除', admin_comment_path(comment), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-sm btn-danger" %>
    </td>
  </tr>
<% end %>
</table>

</div>