config/routes.rb
Rails.application.routes.draw do

# デバイス関係
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers:{
  sessions: "admin/sessions"
  }
  

# ユーザー側
  root to: 'homes#index'
  resources :homes,only: [:index]
  resources :items

  resources :items do
    resources :comments, only: [:create,:destroy],module: 'items'
    resource :likes, only: [:create,:destroy],module: 'items'
    collection do
    resources :searches, only: [:index],module: 'items'
    end
  end

  resources :users do
    # get 'users/my_page' => 'users#show'
    get 'confirm' => "users#confirm"
    patch 'withdraw' => 'users#withdraw'
  end
    
  # resources :users, only: [:edit, :update]
  
  # resources :users do
  #   resources :comments, only: [:create,:destroy],module: 'users'
  # end

  resources :users do
    resources :relationships, only: [:create,:destroy],module: 'users'
  end


# 管理者ルーティング
  namespace :admin do
    resources :comments, only: [:index, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:show, :destroy]
    root to: 'comments#index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  # validates :password, presence: true

# ログイン可能かのメソッド
  def active_for_authentication?
    super && (self.is_active === true)
  end

# 停止中のアカウントへのエラーメッセージ
  def inactive_message
    active_for_authentication? ? super : I18n.t('flash_message.inactive_user')
  end


# ゲストユーザー
GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
      find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "ゲスト"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
# ---

# プロ画表示
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/user.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

# ユーザ名、アイテム名で検索できる
  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["items"]
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "変更が完了しました"
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:is_active)
  end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  def create
  end
    
  def destroy
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :customer_state, only: [:create]
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to items_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  
  def new
  end

  def create
  end
  
  protected
  
# 退会しているかを判断するメソッド
  def customer_state
    # 入力されたemailからアカウントを1件取得
    @user = User.find_by(email: params[:user][:email])
    if @user
    # 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
      if @user.valid_password?(params[:user][:password]) && !@user.is_active
      #一致してるかつ退会してたら（!〇〇.is_active=有効状態の反転）
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_path
      else
          flash[:notice] = "項目を入力してください"
      end
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = current_user
    @items = @user.items.order(created_at: :desc)
    # @item = Item.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path
  end

  def confirm
    @user = User.find(current_user.id)
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_active: false)
    @user.destroy
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private

  def ensure_guest_user
      @user = User.find(params[:id])
      if @user.guest_user?
        redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:profile_image, :name, :email)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/comments_helper.rb
module Users::CommentsHelper
end

app/helpers/users/likes_helper.rb
module Users::LikesHelper
end

app/helpers/users/registration_helper.rb
module Users::RegistrationHelper
end

app/helpers/users/relationships_helper.rb
module Users::RelationshipsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/users/confirm.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col px-0 offset-1">
      
      <div style="text-align: center">
        <h1>本当に退会しますか？</h1>
          <p>
            退会すると、これまでの投稿も削除されてしまいます。<br>
            退会する場合は、「退会する」をクリックしてください。
          </p>
        
          <%= link_to "退会しない", user_path(@user.id), :class => "btn btn-primary ms-3" %>
          <%= link_to "退会する", user_withdraw_path(@user.id), method: :patch, :class => "btn btn-danger ms-3", data: { confirm: "本当に退会しますか？" }  %>
        </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<!--ユーザーの登録情報編集する画面-->
<div class="container">
  <div class="row d-flex justify-content-center">
    <h5 class="border border-white p-3 my-3">
      ユーザー情報編集
    </h5>
  </div>

  <div class="row d-flex justify-content-center">
      <%= form_with model: @user, url: user_path, method: :patch do |f| %>
      <table class="table table-borderless">
          <tr>
            <td width="30%">画像</td>
            <td><%= f.file_field :profile_image, accept: "image/*", class: "rounded" %></td>
          </tr>

          <tr>
            <td width="30%">名前</td>
            <td><%= f.text_field :name, class: "rounded" %></td>
          </tr>

          <td width="30%">メールアドレス</td>
          <td><%= f.text_field :email, class: "rounded" %></td>
          <td></td>
          </tr>
        </table>
          <div class=" d-flex justify-content-center m-2">
            <%= f.submit "編集内容を保存", class:"btn btn-success mx-2" %>
            <%= link_to "退会する", user_confirm_path(@user.id), method: :get, class:"btn btn-danger mx-2" %>
          </div>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--ユーザーマイページ-->
<div class="container">
  <div class="row mb-3">
    <h3>マイページ</h3>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= image_tag @user.get_profile_image(50,50) %>
    </div>
    <div class="col-md-8">
      <%= @user.name %>
    </div>
  </div>

<!--ゲストは編集できないようにする-->
  <% unless @user.guest_user? %>
    <div class="row mt-2">
      <%= link_to "プロフィール編集",edit_user_path(@user),class: "btn btn-secondary edit_user_#{@user.id}" %>
    </div>
  <% end %>
<!---->

<!--投稿したもの-->
  <div class ="row mt-5">
    <h3>投稿</h3>
  </div>

  <div class ="row">
    <div class ="col">
      <table class="table">
        <% @items.each do |item| %>
        <tr>
          <td>
            <%= link_to item_path(item.id) do %>
              <%= image_tag item.get_image(200,200)%>
            <% end %>
          </td>
          <td>
            <%= link_to item_path(item.id) do %>
              <%= item.name %>
            <% end %>
            <!--いいね件数-->
            <td id="items_likes_like_<%= item.id %>" class = "mr-4">
            <%= render 'items/likes/like', item: item %></td>
            <!--コメント件数-->
            <td><%= link_to "#{item.comments.count} コメント", item_path(item.id) %></td>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>