config/routes.rb
Rails.application.routes.draw do

# デバイス関係
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers:{
  sessions: "admin/sessions"
  }
  

# ユーザー側
  root to: 'homes#index'
  resources :homes,only: [:index]
  resources :items

  resources :items do
    resources :comments, only: [:create,:destroy],module: 'items'
    resource :likes, only: [:create,:destroy],module: 'items'
    collection do
    resources :searches, only: [:index],module: 'items'
    end
  end

  resources :users do
    # get 'users/my_page' => 'users#show'
    get 'confirm' => "users#confirm"
    patch 'withdraw' => 'users#withdraw'
  end
    
  # resources :users, only: [:edit, :update]
  
  # resources :users do
  #   resources :comments, only: [:create,:destroy],module: 'users'
  # end

  resources :users do
    resources :relationships, only: [:create,:destroy],module: 'users'
  end


# 管理者ルーティング
  namespace :admin do
    resources :comments, only: [:index, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:show, :destroy]
    root to: 'comments#index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  has_many :likes, dependent: :destroy

  # 中間テーブルを経由してgenreを関連付けている
  has_many :item_genre_relations
  has_many :genres, through: :item_genre_relations
  has_many :comments, dependent: :destroy

  validates :name, presence: true

# 画像に関して
  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(gravity: :center, resize:"#{width}x#{height}^", crop:"#{width}x#{height}+0+0").processed
  end

  # いいね機能で使用↓
  def favorited_by?(user)
    #userがnilの場合falseで返す
    return false unless user.present?
    #likesテーブル内に、user_idが引数として渡されたユーザーのIDと一致し、item_idが自分のアイテムのIDと一致するレコードが存在するかどうかの
    likes.exists?(user_id: user.id)
  end

# 検索機能ransack
  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end

end

app/controllers/items/comments_controller.rb
class Items::CommentsController < ApplicationController
  def create
    item = Item.find(params[:item_id])
    comment = current_user.comments.new(comment_params)
    comment.item_id = item.id
    if comment.save
      redirect_to item_path(item)
    else
      @item = item
      @comment = comment
      render 'items/show'
    end
  end

  def destroy
    item = Item.find(params[:item_id])
    comment = Comment.find(params[:id])
    
    if comment.user_id == current_user.id
      Comment.find(params[:id]).destroy
      redirect_to item_path(item)
    else
      redirect_to item_path(item)
      flash[:alert] = "他人の投稿は削除できません"
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/items/likes_controller.rb
class Items::LikesController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    like = current_user.likes.new(item_id: @item.id)
    like.save
  end

  def destroy
    @item = Item.find(params[:item_id])
    like = current_user.likes.find_by(item_id: @item.id)
    like.destroy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to '/items'
    else
      render :new
    end
  end

  def index
    @q = Item.ransack(params[:q])
      if params[:genre_id].present? #genre_idで検索したら
        @items = Genre.find(params[:genre_id]).items #genre_idで街頭するitemをとってくる
      elsif params[:q].present? #genre_idで検索してなくてransackで検索してたら
        @items = @q.result.includes(:user) #userの検索も含む結果を表示する
      else
        @items = Item.all.order(created_at: :desc) #上のどちらでもない時itemを全て表示する
      end
  end

  def show
    @item = Item.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    begin
    @item = Item.find(params[:id])

    if @item.user_id == current_user.id
      @item.destroy
      redirect_to '/items'
    else
      redirect_to '/items'
      flash[:alert] = "他人の投稿は削除できません"
    end

    rescue ActiveRecord::RecordNotFound
      flash[:alert] = 'その投稿は存在しません'
      redirect_back(fallback_location: '/items')
    end
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:image, :name, :explanation, :price, genre_ids: [])
  end

end

app/helpers/items/searches_helper.rb
module Items::SearchesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_search.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :user_name_or_name_cont, "検索:" %>
  <%= f.search_field :user_name_or_name_cont %>
  <%= f.submit "検索" %>
<% end %>

app/views/items/index.html.erb
<div class="container mt-2">
  <div class ="row">
    <div class="col">
      <h2>投稿一覧</h2>
    </div>
<!--ジャンル検索-->
    <div class="col text-right">
      <%= render 'search', q: @q, url: users_path %>
      <%= form_tag items_path, method: :get do %>
      <%= select_tag :genre_id,
          options_from_collection_for_select(Genre.all, :id, :name, params[:genre_id]),
         { prompt: 'タグで絞り込み検索',onchange: 'submit(this.form);'} %>
      <% end %>
    </div>
  </div>

<!--投稿されたもの↓-->
  <div class="row mt-3">
    <% @items.each do |item| %>
      <div class="card col-md-3">
        <div class="card-header">
    <!--ユーザー情報-->
          <%= image_tag item.user.get_profile_image(35,35) %>
          <%= item.user.name %>
    <!--画像-->
          <%= link_to item_path(item.id) do %>
            <%= image_tag item.get_image(400,400), class:"card-img-top" %>
          <% end %>
        </div>
    <!--内容詳細-->
        <div class="card-body">
          <h5 class="card-title"><%= item.name %></h5>
          <p class="card-text">
            <% item.genres.each do |genre| %>
              <%= genre.name %>
            <% end %>
          </p>
          <p><%= truncate(item.explanation, length: 15) %></p>
    <!--いいね・コメント-->
          <div class = "d-flex">
            <div id="items_likes_like_<%= item.id %>" class = "mr-4">
              <%= render 'items/likes/like', item: item %>
              </div>
            <div><%= link_to "#{item.comments.count} コメント", item_path(item.id) %></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<!--投稿-->
<div class="container">
  <%= render "layouts/errors", obj: @item %>
  <div class="row d-flex justify-content-center">
    <h5 class="border border-white p-3 my-3">
      投稿フォーム
    </h5>
　</div>

    <div class="row d-flex justify-content-center">
     

 　　   <%= form_with model: @item, url: items_path, method: :post do |f| %>
      <table class="table table-borderless">
        <tr>
          <td>画像</td>
          <td><%= f.file_field :image, accept: "image/*", class: "rounded" %></td>
        </tr>

        <tr>
          <td>日本酒名</td>
          <td><%= f.text_field :name, style: "width:70%", placeholder: "商品名", class: "rounded" %></td>
        </tr>

        <tr>
          <td>詳細</td>
          <td><%= f.text_area :explanation, style: "width:70%", rows: "5", placeholder: "ここに説明文を記述します", class: "rounded" %></td>
        </tr>


        <tr>
          <td><%= f.label :genre, 'ジャンル' %></td>
          <td>
            <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) do |genre| %>
              <%= genre.label do %>
                <%= genre.check_box %>
                <%= genre.text %>
              <% end %>
            <% end %>
          </td>
        </tr>

        <tr>
          <td>価格</td>
          <td><%= f.text_field :price, placeholder: "1000", class: "rounded" %>円</td>
        </tr>


    </table>
    <div class="row d-flex justify-content-center">
      <tr>
        <td><%= f.submit "投稿する", class:"btn btn-success" %></td>
      </tr>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<!--投稿詳細画面-->
<div class="container mt-5">
  <%= render "layouts/errors", obj: @comment %>
  <div class="row justify-content-center">
  <!--画像-->
    <div class="col-md-6">
      <%= image_tag @item.image, class:"w-100",style:"aspect-ratio:16/9; object-fit: contain;" %>
    </div>

    <div class="col-md-6">
      <table class="table table-borderless">
    <!--商品名-->
        <tr>
          <td><h3 style="font-weight: bold;"><%= @item.name %></h3></td>
        </tr>
    <!--ジャンル-->
        <tr>
          <td><% @item.genres.each do |genre| %>
              <%= genre.name %>
              <% end %>
          </td>
        </tr>
    <!--詳細-->
        <tr>
          <td><h4><%= @item.explanation %></h4></td>
        </tr>
    <!--価格-->
        <tr>
          <td>￥<%= @item.price %>-</td>
        </tr>

        <tr>
          <td>
            <% if @item.user == current_user %>
              <%= link_to "削除", item_path(@item), method: :delete, data: {confirm: "削除しますか？"} %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row text-right">
    <div class="col">
      <%= link_to '＞＞戻る',items_path %>
    </div>
  </div>


<!--いいね機能-->
<div id="items_likes_like_<%= @item.id %>">
  <%= render 'items/likes/like', item: @item %>
</div>


<!--コメント機能-->
  <div>
    <p>コメント件数：<%= @item.comments.count %></p>
    <% @item.comments.each do |comment| %>
      <p><%= image_tag comment.user.get_profile_image(30,30) %>
      <%= comment.user.name %>
      <%= comment.created_at.strftime('%Y/%m/%d') %>
      <%= comment.comment %>
      <% if comment.user == current_user %>
        <%= link_to "削除", item_comment_path(comment.item, comment), method: :delete, data: {confirm: "削除しますか？"}, remote: true %>
      <% end %></p>
    <% end %>
  </div>
  <div>
    <%= form_with model: [@item, @comment], local: false do |f| %>
      <%= f.text_area :comment, style: "width:100%", rows: '3', placeholder: "コメントをここに" %>
      <%= f.submit "送信する"%>
    <% end %>
  </div>
</div>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>