config/routes.rb
Rails.application.routes.draw do

# デバイス関係
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers:{
  sessions: "admin/sessions"
  }
  

# ユーザー側
  root to: 'homes#index'
  resources :homes,only: [:index]
  resources :items

  resources :items do
    resources :comments, only: [:create,:destroy],module: 'items'
    resource :likes, only: [:create,:destroy],module: 'items'
    collection do
    resources :searches, only: [:index],module: 'items'
    end
  end

  resources :users do
    # get 'users/my_page' => 'users#show'
    get 'confirm' => "users#confirm"
    patch 'withdraw' => 'users#withdraw'
  end
    
  # resources :users, only: [:edit, :update]
  
  # resources :users do
  #   resources :comments, only: [:create,:destroy],module: 'users'
  # end

  resources :users do
    resources :relationships, only: [:create,:destroy],module: 'users'
  end


# 管理者ルーティング
  namespace :admin do
    resources :comments, only: [:index, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:show, :destroy]
    root to: 'comments#index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :item
  
  validates :comment, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  # 中間テーブルを経由してitemを関連付けている
  has_many :item_genre_relations
  has_many :items, through: :item_genre_relations
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  has_many :likes, dependent: :destroy

  # 中間テーブルを経由してgenreを関連付けている
  has_many :item_genre_relations
  has_many :genres, through: :item_genre_relations
  has_many :comments, dependent: :destroy

  validates :name, presence: true

# 画像に関して
  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(gravity: :center, resize:"#{width}x#{height}^", crop:"#{width}x#{height}+0+0").processed
  end

  # いいね機能で使用↓
  def favorited_by?(user)
    #userがnilの場合falseで返す
    return false unless user.present?
    #likesテーブル内に、user_idが引数として渡されたユーザーのIDと一致し、item_idが自分のアイテムのIDと一致するレコードが存在するかどうかの
    likes.exists?(user_id: user.id)
  end

# 検索機能ransack
  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end

end

app/models/item_genre_relation.rb
class ItemGenreRelation < ApplicationRecord
  belongs_to :item
  belongs_to :genre
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
  
  validates :user_id, uniqueness: {scope: :item_id}
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  # validates :password, presence: true

# ログイン可能かのメソッド
  def active_for_authentication?
    super && (self.is_active === true)
  end

# 停止中のアカウントへのエラーメッセージ
  def inactive_message
    active_for_authentication? ? super : I18n.t('flash_message.inactive_user')
  end


# ゲストユーザー
GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
      find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "ゲスト"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
# ---

# プロ画表示
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/user.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

# ユーザ名、アイテム名で検索できる
  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["items"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def admin_url
    request.fullpath.include?("/admin")
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_comments_path
    when User
      items_path
    end
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to '/items'
    else
      render :new
    end
  end

  def index
    @q = Item.ransack(params[:q])
      if params[:genre_id].present? #genre_idで検索したら
        @items = Genre.find(params[:genre_id]).items #genre_idで街頭するitemをとってくる
      elsif params[:q].present? #genre_idで検索してなくてransackで検索してたら
        @items = @q.result.includes(:user) #userの検索も含む結果を表示する
      else
        @items = Item.all.order(created_at: :desc) #上のどちらでもない時itemを全て表示する
      end
  end

  def show
    @item = Item.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    begin
    @item = Item.find(params[:id])

    if @item.user_id == current_user.id
      @item.destroy
      redirect_to '/items'
    else
      redirect_to '/items'
      flash[:alert] = "他人の投稿は削除できません"
    end

    rescue ActiveRecord::RecordNotFound
      flash[:alert] = 'その投稿は存在しません'
      redirect_back(fallback_location: '/items')
    end
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:image, :name, :explanation, :price, genre_ids: [])
  end

end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = current_user
    @items = @user.items.order(created_at: :desc)
    # @item = Item.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path
  end

  def confirm
    @user = User.find(current_user.id)
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_active: false)
    @user.destroy
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private

  def ensure_guest_user
      @user = User.find(params[:id])
      if @user.guest_user?
        redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:profile_image, :name, :email)
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row d-flex justify-content-center">
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <link href="https://fonts.googleapis.com/css?family=Sawarabi+Mincho" rel="stylesheet">
  <script src="https://kit.fontawesome.com/df90ce326d.js" crossorigin="anonymous"></script>
    <head>
      <title>nihonsyu noren</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_link_tag 'custom' %>
      <style>
        .btn-lee {
            color: #fff;
            background-color: #96514d;
            border-color: #96514d;
        }
      </style>
    </head>

    <body style="background-color: #d4dcd6;">
      <header>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #0f2350;">
        <div class="container">
          <div class="d-flex">
            <a class="navbar-brand" href="/"><%= image_tag 'logo.jpg', :size =>'100x100' %></a>
            <% if user_signed_in? %>
              <div class="nav-item text-light my-auto ml-4">
                ようこそ、<%= current_user.name %>さん！
              </div>
            <% end %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'マイページ', user_path(current_user), class: 'nav-link text-light m-2' %>
                </li>

                <li class="nav-item">
                  <%= link_to '投稿', new_item_path, class: 'nav-link text-light m-2' %>
                </li>

                <li class="nav-item">
                  <%= link_to "投稿一覧", items_path, class: 'nav-link text-light m-2' %>
                </li>


                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-light m-2' %>
                </li>

              <% elsif admin_signed_in? %>

                <li class="nav-item">
                  <%= link_to "ユーザー一覧", admin_users_path, class: 'nav-link text-light m-2' %>
                </li>
                <li class="nav-item">
                  <%= link_to "コメント一覧", admin_comments_path, class: 'nav-link text-light m-2' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light m-2' %>
                </li>

              <% else %>

                <li class="nav-item">
                  <%= link_to "トップ", root_path, class: 'nav-link text-light m-2' %>
                </li>

                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-light m-2' %>
                </li>

                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-light m-2' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      </header>

    <main class="pb-1" style="background-color: #d4dcd6;">
      <div id="messages">
        <div class="d-flex justify-content-center">
          <p class="notice alert-info px-3" role="alert"><%= notice %></p>
        </div>
        <div class="d-flex justify-content-center">
          <p class="arlet alert-danger px-3" role="alert"><%= alert %></p>
        </div>
      </div>
    <%= yield %>
    </main>

    <footer class='fixed-bottom text-light' style="background-color: #0f2350;">
      <div class="container">
        	<div class='row'>
          	<div class='mx-auto my-2'>
          		<h5>日本酒のれん</h5>
          	</div>
          </div>
      </div>
    </footer>
    <script>
      document.addEventListener('turbolinks:load',()=>{
        setTimeout(()=>{
          document.getElementById('messages').style.opacity=0
        },3000)
      })
    </script>
  </body>
</html>